### ISSUE TITLE
Allocation issue

### ISSUE THREAD

**Issue by jay-a-brown** [WolfWings/v4l2-fm-radio#1]
Compiled it (make / no issues)  on a Ubuntu 18.04 box with 32 gb ram, (dell 7530)

Connected to an rtl-sdr (as a baseline test) 
```
./player 95.5 
Failed to allocate input buffer!
RIFF����WAVEfmt }�data����
```
I only have about 8 gb of my 32gb  in use.  
Any ideas why it thinks it can't allocate (2048 * 1024) ?  

I added some code to check errno and it is returning 
   ENOMEM          Not enough space/cannot allocate memory
                    
My C is really rusty (haven't used for over 20 years) but this seems odd to me.   Wondered if you had any suggestions.    Very interested to see this code work!  Thank you for posting.

**Comment by WolfWings** [comment]
This was an oversight on my part as I'd chopped down a video stream capture tool I'd been developing for the initial player, thank you for bringing this to my attention. I've resolved it in 4beebec6329f3dee188c7f8e9ea7ae2544b7ff3d
